// typescript/native-auth/react-nextjs-sample/src/app/sign-up/page.tsx
"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { customAuthConfig } from "../../config/auth-config";
import { styles } from "./styles/styles";
import { EmailStep } from "./components/EmailStep";
import { EmailCodeStep } from "./components/EmailCodeStep";
import { DetailsStep } from "./components/DetailsStep";
import { MobileStep } from "./components/MobileStep";
import { SmsCodeStep } from "./components/SmsCodeStep";
import {
    AuthFlowStateBase,
    CustomAuthAccountData,
    CustomAuthPublicClientApplication,
    ICustomAuthPublicClientApplication,
    SignInCompletedState,
    SignUpAttributesRequiredState,
    SignUpCodeRequiredState,
    SignUpCompletedState,
    SignUpPasswordRequiredState,
    UserAccountAttributes,
    AuthMethodRegistrationRequiredState,
    AuthMethodVerificationRequiredState,
    AuthenticationMethod,
    MfaAwaitingState,
    MfaVerificationRequiredState,
    InvalidArgumentError,
} from "@azure/msal-browser/custom-auth";
import { MfaAuthMethodSelectionForm } from "../shared/components/MfaAuthMethodSelectionForm";
import { MfaChallengeForm } from "../shared/components/MfaChallengeForm";

type UiStep = "email" | "emailCode" | "details";

export default function SignUpPage() {
    const router = useRouter();
    const [authClient, setAuthClient] = useState<ICustomAuthPublicClientApplication | null>(null);

    const [uiStep, setUiStep] = useState<UiStep>("email");

    const [email, setEmail] = useState("");
    const [emailCode, setEmailCode] = useState("");
    const [password, setPassword] = useState("");
    const [confirmPassword, setConfirmPassword] = useState("");
    const [givenName, setGivenName] = useState("");
    const [familyName, setFamilyName] = useState("");
    const [dateOfBirth, setDateOfBirth] = useState("");
    const [termsAccepted, setTermsAccepted] = useState(false);
    const [mobileNumber, setMobileNumber] = useState("");
    const [smsCode, setSmsCode] = useState("");

    const [error, setError] = useState("");
    const [loading, setLoading] = useState(false);
    const [signUpState, setSignUpState] = useState<AuthFlowStateBase | null>(null);
    const [loadingAccountStatus, setLoadingAccountStatus] = useState(true);
    const [isSignedIn, setSignInState] = useState(false);
    const [data, setData] = useState<CustomAuthAccountData | undefined>(undefined);

    const [phoneAuthMethod, setPhoneAuthMethod] = useState<AuthenticationMethod | undefined>(undefined);

    // MFA states (kept for future SMS MFA sign-in flow)
    const [mfaAuthMethods, setMfaAuthMethods] = useState<AuthenticationMethod[]>([]);
    const [selectedMfaAuthMethod, setSelectedMfaAuthMethod] = useState<AuthenticationMethod | undefined>(undefined);
    const [mfaChallenge, setMfaChallenge] = useState("");

    useEffect(() => {
        const initializeApp = async () => {
            const appInstance = await CustomAuthPublicClientApplication.create(customAuthConfig);
            setAuthClient(appInstance);
        };

        initializeApp();
    }, []);

    useEffect(() => {
        const checkAccount = async () => {
            if (!authClient) return;

            const accountResult = authClient.getCurrentAccount();
            if (accountResult.isCompleted()) {
                setSignInState(true);
            }
            setLoadingAccountStatus(false);
        };

        checkAccount();
    }, [authClient]);

    const handleCancel = () => {
        router.push("/");
    };

    const handleResendCode = async () => {
        if (!authClient || !email) return;
        setError("");
        setLoading(true);
        try {
            const result = await authClient.signUp({ username: email });
            const state = result.state;
            if (result.isFailed()) {
                setError(result.error?.errorData.errorDescription || "Failed to resend the code.");
                return;
            }
            if (state instanceof SignUpCodeRequiredState) {
                setSignUpState(state);
            }
        } catch (err) {
            handleSubmitException(err, "Failed to resend the code.");
        } finally {
            setLoading(false);
        }
    };

    const resetSignUpToStart = (message: string) => {
        setSignUpState(null);
        setUiStep("email");
        setEmailCode("");
        setPassword("");
        setConfirmPassword("");
        setGivenName("");
        setFamilyName("");
        setDateOfBirth("");
        setTermsAccepted(false);
        setMobileNumber("");
        setSmsCode("");
        setMfaAuthMethods([]);
        setSelectedMfaAuthMethod(undefined);
        setMfaChallenge("");
        setPhoneAuthMethod(undefined);
        setError(message);
    };

    const handleSubmitException = (err: unknown, fallback: string): void => {
        if (err instanceof InvalidArgumentError) {
            const desc = err.errorDescription ?? "";
            if (desc.includes("code") || desc.includes("challenge")) {
                setError("Please enter the full verification code.");
                return;
            }
            if (desc.includes("password")) {
                setError("Please enter your password.");
                return;
            }
            if (desc.includes("attributes")) {
                setError("Please fill in all required details.");
                return;
            }
            setError(fallback);
            return;
        }
        throw err;
    };

    const handleEmailSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        setError("");
        if (!authClient) return;
        setLoading(true);

        try {
            const result = await authClient.signUp({ username: email });
            const state = result.state;

            if (result.isFailed()) {
                if (result.error?.isUserAlreadyExists()) {
                    setError("An account with this email already exists.");
                } else if (result.error?.isInvalidUsername()) {
                    setError("Invalid email address.");
                } else {
                    setError(result.error?.errorData.errorDescription || "An error occurred while signing up.");
                }
                return;
            }

            if (state instanceof SignUpCodeRequiredState) {
                setSignUpState(state);
                setUiStep("emailCode");
                return;
            }

            if (
                state instanceof SignUpPasswordRequiredState ||
                state instanceof SignUpAttributesRequiredState
            ) {
                setSignUpState(state);
                setUiStep("details");
                return;
            }

            setError("Unexpected sign-up state — email verification was not requested.");
        } catch (err) {
            handleSubmitException(err, "An error occurred while signing up.");
        } finally {
            setLoading(false);
        }
    };

    const handleEmailCodeSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        setError("");
        if (!(signUpState instanceof SignUpCodeRequiredState)) {
            setError("Sign-up session was lost. Please start again.");
            return;
        }
        setLoading(true);

        try {
            const result = await signUpState.submitCode(emailCode);
            const state = result.state;

            if (result.isFailed()) {
                if (result.error?.isTokenExpired()) {
                    resetSignUpToStart("Your sign-up session expired. Please start again.");
                } else if (result.error?.isInvalidCode()) {
                    setError("The email verification code is invalid. Please re-enter.");
                } else {
                    setError(result.error?.errorData.errorDescription || "Failed to verify the email code.");
                }
                return;
            }

            if (state instanceof SignUpCompletedState) {
                await handleAutoSignIn(state);
                return;
            }

            setSignUpState(state);
            setUiStep("details");
        } catch (err) {
            handleSubmitException(err, "Failed to verify the email code.");
        } finally {
            setLoading(false);
        }
    };

    const handleDetailsSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        setError("");
        if (!authClient) return;
        setLoading(true);

        try {
            const attributes: UserAccountAttributes = {
                displayName: `${givenName} ${familyName}`.trim(),
                givenName,
                surname: familyName,
                dateOfBirth,
            } as UserAccountAttributes;

            let nextState: AuthFlowStateBase | null = signUpState;

            if (nextState instanceof SignUpPasswordRequiredState) {
                const pwResult = await nextState.submitPassword(password);
                const stateAfterPw = pwResult.state;

                if (pwResult.isFailed()) {
                    if (pwResult.error?.isTokenExpired()) {
                        resetSignUpToStart("Your sign-up session expired. Please start again.");
                    } else if (pwResult.error?.isInvalidPassword()) {
                        setError("Invalid password.");
                    } else {
                        setError(pwResult.error?.errorData.errorDescription || "Failed to submit password.");
                    }
                    return;
                }
                nextState = stateAfterPw;
            }

            if (nextState instanceof SignUpAttributesRequiredState) {
                const attrResult = await nextState.submitAttributes(attributes);
                const stateAfterAttr = attrResult.state;

                if (attrResult.isFailed()) {
                    if (attrResult.error?.isTokenExpired()) {
                        resetSignUpToStart("Your sign-up session expired. Please start again.");
                    } else if (attrResult.error?.isAttributesValidationFailed()) {
                        setError("One or more details are invalid.");
                    } else if (attrResult.error?.isMissingRequiredAttributes()) {
                        setError("Missing required details.");
                    } else {
                        setError(attrResult.error?.errorData.errorDescription || "Failed to submit details.");
                    }
                    return;
                }
                nextState = stateAfterAttr;
            }

            if (nextState instanceof SignUpCompletedState) {
                await handleAutoSignIn(nextState);
                return;
            }

            if (nextState) {
                setSignUpState(nextState);
            }
        } catch (err) {
            handleSubmitException(err, "Failed to submit details.");
        } finally {
            setLoading(false);
        }
    };

    const handleAutoSignIn = async (completedState: SignUpCompletedState) => {
        const result = await completedState.signIn();

        if (result.isFailed()) {
            setError(result.error?.errorData?.errorDescription || "An error occurred during auto sign-in.");
        }

        if (result.isAuthMethodRegistrationRequired()) {
            const methods = result.state.getAuthMethods();
            const phone = pickPhoneMethod(methods);
            setPhoneAuthMethod(phone);
            setSignUpState(result.state);
            return;
        }

        if (result.isMfaRequired()) {
            const methods = result.state.getAuthMethods();
            setMfaAuthMethods(methods);
            setSelectedMfaAuthMethod(methods.length > 0 ? methods[0] : undefined);
            setSignUpState(result.state);
            return;
        }

        if (result.isCompleted()) {
            setData(result.data);
            setSignUpState(result.state);
            setSignInState(true);
        }
    };

    const pickPhoneMethod = (methods: AuthenticationMethod[]): AuthenticationMethod | undefined => {
        const phone = methods.find((m) => {
            const ch = m.challenge_channel?.toLowerCase();
            return ch === "sms" || ch === "phone";
        });
        return phone ?? methods[0];
    };

    const handleMobileSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        setError("");

        if (!(signUpState instanceof AuthMethodRegistrationRequiredState)) return;
        if (!phoneAuthMethod) {
            setError("No phone authentication method is available for this account.");
            return;
        }

        setLoading(true);
        try {
            const result = await signUpState.challengeAuthMethod({
                authMethodType: phoneAuthMethod,
                verificationContact: mobileNumber,
            });

            if (result.isFailed()) {
                if (result.error?.isTokenExpired()) {
                    resetSignUpToStart("Your sign-up session expired. Please start again.");
                    return;
                } else if (result.error?.isInvalidInput && result.error.isInvalidInput()) {
                    setError("The mobile number is invalid.");
                } else if (result.error?.isVerificationContactBlocked()) {
                    setError("This mobile number is blocked. Please use a different number.");
                } else {
                    setError(
                        result.error?.errorData?.errorDescription || "An error occurred while sending the SMS code."
                    );
                }
            }

            if (result.isCompleted()) {
                setData(result.data);
                setSignUpState(result.state);
                setSignInState(true);
            }

            if (result.isVerificationRequired && result.isVerificationRequired()) {
                setSignUpState(result.state);
            }
        } catch (err) {
            handleSubmitException(err, "An error occurred while sending the SMS code.");
        } finally {
            setLoading(false);
        }
    };

    const handleSmsCodeSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        setError("");

        if (!(signUpState instanceof AuthMethodVerificationRequiredState)) return;

        setLoading(true);
        try {
            const result = await signUpState.submitChallenge(smsCode);

            if (result.isFailed()) {
                if (result.error?.isTokenExpired()) {
                    resetSignUpToStart("Your sign-up session expired. Please start again.");
                    return;
                } else if (result.error?.isIncorrectChallenge && result.error.isIncorrectChallenge()) {
                    setError("Incorrect code.");
                } else {
                    setError(
                        result.error?.errorData?.errorDescription || "An error occurred while verifying the SMS code."
                    );
                }
            }

            if (result.isCompleted()) {
                setData(result.data);
                setSignUpState(result.state);
                setSignInState(true);
            }
        } catch (err) {
            handleSubmitException(err, "An error occurred while verifying the SMS code.");
        } finally {
            setLoading(false);
        }
    };

    const handleMfaAuthMethodSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        setError("");
        setLoading(true);

        if (!selectedMfaAuthMethod) {
            setError("Please select an authentication method.");
            setLoading(false);
            return;
        }

        if (signUpState instanceof MfaAwaitingState) {
            try {
                const result = await signUpState.requestChallenge(selectedMfaAuthMethod.id);

                if (result.isFailed()) {
                    if (result.error?.isTokenExpired()) {
                        resetSignUpToStart("Your sign-up session expired. Please start again.");
                    } else if (result.error?.isInvalidInput()) {
                        setError("Incorrect verification contact.");
                    } else {
                        setError(
                            result.error?.errorData?.errorDescription ||
                                "An error occurred while verifying the authentication method"
                        );
                    }
                }

                if (result.isVerificationRequired()) {
                    setSignUpState(result.state);
                }
            } catch (err) {
                handleSubmitException(err, "An error occurred while verifying the authentication method");
            }
        }

        setLoading(false);
    };

    const handleMfaChallengeSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        setError("");
        setLoading(true);

        if (!mfaChallenge) {
            setError("Please enter a code.");
            setLoading(false);
            return;
        }

        if (signUpState instanceof MfaVerificationRequiredState) {
            try {
                const result = await signUpState.submitChallenge(mfaChallenge);

                if (result.isFailed()) {
                    if (result.error?.isTokenExpired()) {
                        resetSignUpToStart("Your sign-up session expired. Please start again.");
                    } else if (result.error?.isIncorrectChallenge()) {
                        setError("Incorrect code.");
                    } else {
                        setError(
                            result.error?.errorData?.errorDescription ||
                                "An error occurred while verifying the challenge response"
                        );
                    }
                }

                if (result.isCompleted()) {
                    setData(result.data);
                    setSignInState(true);
                    setSignUpState(result.state);
                }
            } catch (err) {
                handleSubmitException(err, "An error occurred while verifying the challenge response");
            }
        }

        setLoading(false);
    };

    const renderForm = () => {
        if (loadingAccountStatus) return null;

        if (isSignedIn) {
            return <div style={styles.signed_in_msg}>Please sign out before processing the sign up.</div>;
        }

        if (signUpState instanceof AuthMethodRegistrationRequiredState) {
            return (
                <MobileStep
                    onSubmit={handleMobileSubmit}
                    mobileNumber={mobileNumber}
                    setMobileNumber={setMobileNumber}
                    loading={loading}
                />
            );
        }

        if (signUpState instanceof AuthMethodVerificationRequiredState) {
            return (
                <SmsCodeStep
                    onSubmit={handleSmsCodeSubmit}
                    code={smsCode}
                    setCode={setSmsCode}
                    loading={loading}
                />
            );
        }

        if (signUpState instanceof MfaAwaitingState) {
            return (
                <MfaAuthMethodSelectionForm
                    onSubmit={handleMfaAuthMethodSubmit}
                    authMethods={mfaAuthMethods}
                    selectedAuthMethod={selectedMfaAuthMethod}
                    setSelectedAuthMethod={setSelectedMfaAuthMethod}
                    loading={loading}
                    styles={styles}
                />
            );
        }

        if (signUpState instanceof MfaVerificationRequiredState) {
            return (
                <MfaChallengeForm
                    onSubmit={handleMfaChallengeSubmit}
                    challenge={mfaChallenge}
                    setChallenge={setMfaChallenge}
                    loading={loading}
                    styles={styles}
                />
            );
        }

        if (signUpState instanceof SignInCompletedState) {
            return (
                <div style={styles.signed_in_msg}>
                    Sign up completed! Automatically signed in as {data?.getAccount().username}
                </div>
            );
        }

        if (uiStep === "email") {
            return (
                <EmailStep
                    onSubmit={handleEmailSubmit}
                    email={email}
                    setEmail={setEmail}
                    loading={loading}
                    onCancel={handleCancel}
                />
            );
        }

        if (uiStep === "emailCode") {
            return (
                <EmailCodeStep
                    onSubmit={handleEmailCodeSubmit}
                    code={emailCode}
                    setCode={setEmailCode}
                    loading={loading}
                    email={email}
                    onCancel={handleCancel}
                    onResend={handleResendCode}
                />
            );
        }

        return (
            <DetailsStep
                onSubmit={handleDetailsSubmit}
                password={password}
                setPassword={setPassword}
                confirmPassword={confirmPassword}
                setConfirmPassword={setConfirmPassword}
                givenName={givenName}
                setGivenName={setGivenName}
                familyName={familyName}
                setFamilyName={setFamilyName}
                dateOfBirth={dateOfBirth}
                setDateOfBirth={setDateOfBirth}
                termsAccepted={termsAccepted}
                setTermsAccepted={setTermsAccepted}
                loading={loading}
            />
        );
    };

    return (
        <div style={styles.pageWrapper}>
            <div style={styles.hero}>
                <div style={styles.heroInner}>
                    <h1 style={styles.heroTitle}>Welcome to myServiceTas</h1>
                </div>
            </div>
            <div style={styles.card}>
                <div style={styles.cardInner}>
                    {renderForm()}
                    {error && <div style={styles.error}>{error}</div>}
                </div>
            </div>
        </div>
    );
}

// typescript/native-auth/angular-sample/src/app/components/sign-up/sign-up.component.ts
import { Component } from "@angular/core";
import { AuthService } from "../../services/auth.service";
import {
    SignUpPasswordRequiredState,
    SignUpCodeRequiredState,
    SignUpCompletedState,
    UserAccountAttributes,
    AuthenticationMethod,
    AuthMethodRegistrationRequiredState,
    AuthMethodVerificationRequiredState,
    MfaAwaitingState,
    MfaVerificationRequiredState,
} from "@azure/msal-browser/custom-auth";
import { CommonModule } from "@angular/common";
import { FormsModule } from "@angular/forms";
import { PopupRequest } from "@azure/msal-browser";
import { customAuthConfig } from "../../config/auth-config";
import { CodeFormComponent } from "../shared/code-form/code-form.component";
import { PasswordFormComponent } from "../shared/password-form/password-form.component";
import { AuthMethodSelectionFormComponent } from "../shared/auth-method-selection-form/auth-method-selection-form.component";
import { AuthMethodChallengeFormComponent } from "../shared/auth-method-challenge-form/auth-method-challenge-form.component";
import { MfaAuthMethodSelectionFormComponent } from "../shared/mfa-auth-method-selection-form/mfa-auth-method-selection-form.component";
import { MfaChallengeFormComponent } from "../shared/mfa-challenge-form/mfa-challenge-form.component";

@Component({
    selector: "app-sign-up",
    templateUrl: "./sign-up.component.html",
    standalone: true,
    imports: [
        CommonModule,
        FormsModule,
        CodeFormComponent,
        PasswordFormComponent,
        AuthMethodSelectionFormComponent,
        AuthMethodChallengeFormComponent,
        MfaAuthMethodSelectionFormComponent,
        MfaChallengeFormComponent,
    ],
})
export class SignUpComponent {
    firstName = "";
    lastName = "";
    jobTitle = "";
    city = "";
    country = "";
    email = "";
    flatUsername = "";
    password = "";
    code = "";
    error = "";
    loading = false;
    showPassword = false;
    showCode = false;
    showAuthMethodsForRegistration = false;
    showChallengeForRegistration = false;
    showMfaAuthMethods = false;
    showMfaChallenge = false;
    authMethodsForRegistration: AuthenticationMethod[] = [];
    selectedAuthMethodForRegistration: AuthenticationMethod | undefined = undefined;
    verificationContactForRegistration: string | undefined = undefined;
    challengeForRegistration: string | undefined = undefined;
    mfaAuthMethods: AuthenticationMethod[] = [];
    selectedMfaAuthMethod: AuthenticationMethod | undefined = undefined;
    mfaChallenge: string | undefined = undefined;
    isSignedUp = false;
    isSignedIn = false;
    userData: any = null;
    signUpState: any = null;
    resendCountdown = 0;

    socialProviders = [
        { name: "Google", domainHint: "Google", logo: "/logos/google.svg" },
        { name: "Facebook", domainHint: "Facebook", logo: "/logos/facebook.svg" },
        { name: "Apple", domainHint: "Apple", logo: "/logos/apple.svg" },
        { name: "LinkedIn", domainHint: "www.linkedin.com", logo: "/logos/linkedin.svg" },
    ];

    constructor(private auth: AuthService) {}

    async ngOnInit() {
        const client = await this.auth.getClient();
        const result = client.getCurrentAccount();
        if (result.isCompleted()) {
            this.isSignedIn = true;
            this.showCode = false;
            this.showPassword = false;
            this.userData = result.data;
        }
    }

    async startSignUp() {
        this.error = "";
        this.loading = true;
        this.isSignedUp = false;
        this.showPassword = false;
        this.showCode = false;
        this.signUpState = null;

        const client = await this.auth.getClient();
        const attributes: UserAccountAttributes = {
            displayName: this.firstName || this.lastName,
            givenName: this.firstName,
            surname: this.lastName,
            jobTitle: this.jobTitle,
            city: this.city,
            country: this.country,
            flatusername: this.flatUsername,
        };

        const result = await client.signUp({
            username: this.email,
            attributes,
        });

        if (result.isFailed()) {
            if (result.error?.isUserAlreadyExists()) {
                this.error = "An account with this email or username already exists";
            } else if (result.error?.isInvalidUsername()) {
                this.error = "Invalid username";
            } else if (result.error?.isInvalidPassword()) {
                this.error = "Invalid password";
            } else if (result.error?.isAttributesValidationFailed()) {
                this.error = "Invalid attributes";
            } else if (result.error?.isMissingRequiredAttributes()) {
                this.error = "Missing required attributes";
            } else {
                this.error = result.error?.errorData.errorDescription || "An error occurred while signing up";
            }
        }

        this.signUpState = result.state;

        if (result.isPasswordRequired()) {
            this.showPassword = true;
            this.showCode = false;
        } else if (result.isCodeRequired()) {
            this.showPassword = false;
            this.showCode = true;
        }

        this.loading = false;
    }

    async submitPassword() {
        this.error = "";
        this.loading = true;
        if (this.signUpState instanceof SignUpPasswordRequiredState) {
            const result = await this.signUpState.submitPassword(this.password);

            if (result.isFailed()) {
                if (result.error?.isInvalidPassword()) {
                    this.error = "Invalid password";
                } else {
                    this.error =
                        result.error?.errorData.errorDescription || "An error occurred while submitting the password";
                }
            }

            if (result.isCompleted()) {
                this.isSignedUp = true;
                this.showPassword = false;
                this.showCode = false;
                this.signUpState = result.state;
                this.handleAutoSignIn();
            }
        }
        this.loading = false;
    }

    async submitCode() {
        this.error = "";
        this.loading = true;
        if (this.signUpState instanceof SignUpCodeRequiredState) {
            const result = await this.signUpState.submitCode(this.code);

            if (result.isFailed()) {
                if (result.error?.isInvalidCode()) {
                    this.error = "Invalid verification code";
                } else {
                    this.error =
                        result.error?.errorData.errorDescription || "An error occurred while verifying the code";
                }
            }

            if (result.isCompleted()) {
                this.isSignedUp = true;
                this.showCode = false;
                this.showPassword = false;
                this.signUpState = result.state;
                this.handleAutoSignIn();
            } else if (result.isPasswordRequired()) {
                this.showCode = false;
                this.showPassword = true;
                this.signUpState = result.state;
            }
        }
        this.loading = false;
    }

    async resendCode() {
        this.error = "";
        this.loading = false;

        if (this.signUpState instanceof SignUpCodeRequiredState) {
            const result = await this.signUpState.resendCode();

            if (result.isFailed()) {
                this.error = result.error?.errorData.errorDescription || "An error occurred while resending the code";
            } else {
                this.resendCountdown = 30;

                const timer = setInterval(() => {
                    this.resendCountdown--;
                    if (this.resendCountdown <= 0) {
                        clearInterval(timer);
                        this.resendCountdown = 0;
                    }
                }, 1000);
            }
        }
    }

    async submitAuthMethodForRegistration() {
        this.error = "";
        this.loading = true;

        if (!this.selectedAuthMethodForRegistration || !this.verificationContactForRegistration) {
            this.error = "Please select an authentication method and enter a verification contact.";
            this.loading = false;
            return;
        }

        if (this.signUpState instanceof AuthMethodRegistrationRequiredState) {
            const result = await this.signUpState.challengeAuthMethod({
                authMethodType: this.selectedAuthMethodForRegistration,
                verificationContact: this.verificationContactForRegistration,
            });

            if (result.isFailed()) {
                if (result.error?.isInvalidInput()) {
                    this.error = "Incorrect verification contact.";
                } else if (result.error?.isVerificationContactBlocked()) {
                    this.error =
                        "The verification contact is blocked. Consider using a different contact or a different authentication method";
                } else {
                    this.error =
                        result.error?.errorData?.errorDescription ||
                        "An error occurred while verifying the authentication method";
                }
            }

            if (result.isCompleted()) {
                this.isSignedIn = true;
                this.userData = result.data;
                this.showAuthMethodsForRegistration = false;
                this.signUpState = result.state;
            }

            if (result.isVerificationRequired()) {
                this.showAuthMethodsForRegistration = false;
                this.showChallengeForRegistration = true;
                this.signUpState = result.state;
            }
        }
        this.loading = false;
    }

    async submitChallengeForRegistration() {
        this.error = "";
        this.loading = true;

        if (!this.challengeForRegistration) {
            this.error = "Please enter a code.";
            this.loading = false;
            return;
        }

        if (this.signUpState instanceof AuthMethodVerificationRequiredState) {
            const result = await this.signUpState.submitChallenge(this.challengeForRegistration);

            if (result.isFailed()) {
                if (result.error?.isIncorrectChallenge()) {
                    this.error = "Incorrect code.";
                } else {
                    this.error =
                        result.error?.errorData?.errorDescription ||
                        "An error occurred while verifying the challenge response";
                }
            }

            if (result.isCompleted()) {
                this.isSignedIn = true;
                this.userData = result.data;
                this.showChallengeForRegistration = false;
                this.signUpState = result.state;
            }
        }
        this.loading = false;
    }

    async submitMfaAuthMethod() {
        this.error = "";
        this.loading = true;

        if (!this.selectedMfaAuthMethod) {
            this.error = "Please select an authentication method.";
            this.loading = false;
            return;
        }

        if (this.signUpState instanceof MfaAwaitingState) {
            const result = await this.signUpState.requestChallenge(this.selectedMfaAuthMethod.id);

            if (result.isFailed()) {
                if (result.error?.isInvalidInput()) {
                    this.error = "Incorrect verification contact.";
                } else {
                    this.error =
                        result.error?.errorData?.errorDescription ||
                        "An error occurred while verifying the authentication method";
                }
            }

            if (result.isVerificationRequired()) {
                this.showMfaAuthMethods = false;
                this.showMfaChallenge = true;
                this.signUpState = result.state;
            }
        }
        this.loading = false;
    }

    async submitMfaChallenge() {
        this.error = "";
        this.loading = true;

        if (!this.mfaChallenge) {
            this.error = "Please enter a code.";
            this.loading = false;
            return;
        }

        if (this.signUpState instanceof MfaVerificationRequiredState) {
            const result = await this.signUpState.submitChallenge(this.mfaChallenge);

            if (result.isFailed()) {
                if (result.error?.isIncorrectChallenge()) {
                    this.error = "Incorrect code.";
                } else {
                    this.error =
                        result.error?.errorData?.errorDescription ||
                        "An error occurred while verifying the challenge response";
                }
            }

            if (result.isCompleted()) {
                this.isSignedIn = true;
                this.userData = result.data;
                this.showMfaChallenge = false;
                this.signUpState = result.state;
            }
        }
        this.loading = false;
    }

    getPlaceholderTextForVerificationContact(): string {
        if (!this.selectedAuthMethodForRegistration) {
            return "Enter your contact information";
        }

        const channel = this.selectedAuthMethodForRegistration.challenge_channel?.toLowerCase();
        if (channel === "email") {
            return "Enter your email for verification";
        } else if (channel === "sms" || channel === "phone") {
            return "Enter your phone number for verification";
        } else {
            return "Enter your contact information for verification";
        }
    }

    private async handleAutoSignIn() {
        this.error = "";

        if (this.signUpState instanceof SignUpCompletedState) {
            const result = await this.signUpState.signIn();

            if (result.isFailed()) {
                this.error = result.error?.errorData?.errorDescription || "An error occurred during auto sign-in";
            }

            if (result.isAuthMethodRegistrationRequired()) {
                this.showAuthMethodsForRegistration = true;
                this.showPassword = false;
                this.showCode = false;
                this.showChallengeForRegistration = false;
                this.showMfaAuthMethods = false;
                this.showMfaChallenge = false;
                this.authMethodsForRegistration = result.state.getAuthMethods();
                // Set default selection to the first auth method
                this.selectedAuthMethodForRegistration =
                    this.authMethodsForRegistration.length > 0 ? this.authMethodsForRegistration[0] : undefined;
                this.signUpState = result.state;
            } else if (result.isMfaRequired()) {
                this.showMfaAuthMethods = true;
                this.showPassword = false;
                this.showCode = false;
                this.showAuthMethodsForRegistration = false;
                this.showChallengeForRegistration = false;
                this.showMfaChallenge = false;
                this.mfaAuthMethods = result.state.getAuthMethods();
                // Set default selection to the first MFA auth method
                this.selectedMfaAuthMethod = this.mfaAuthMethods.length > 0 ? this.mfaAuthMethods[0] : undefined;
                this.signUpState = result.state;
            } else if (result.isCompleted()) {
                this.userData = result.data;
                this.signUpState = result.state;
                this.isSignedUp = true;
                this.showCode = false;
                this.showPassword = false;
                this.showAuthMethodsForRegistration = false;
                this.showChallengeForRegistration = false;
                this.showMfaAuthMethods = false;
                this.showMfaChallenge = false;
            }
        }
    }

    async startSignUpWithSocial(domainHint: string) {
        this.error = "";
        this.loading = false;

        const popUpRequest: PopupRequest = {
            authority: customAuthConfig.auth.authority,
            scopes: [],
            redirectUri: customAuthConfig.auth.redirectUri || "",
            prompt: "login",
            domainHint: domainHint,
        };

        try {
            const client = await this.auth.getClient();

            await client.loginPopup(popUpRequest);

            const accountResult = client.getCurrentAccount();

            if (accountResult.isFailed()) {
                this.error =
                    accountResult.error?.errorData?.errorDescription ??
                    "An error occurred while getting the account from cache";
            }

            if (accountResult.isCompleted()) {
                this.userData = accountResult.data;
                this.isSignedIn = true;
            }
        } catch (error) {
            if (error instanceof Error) {
                this.error = error.message;
            } else {
                this.error = "An unexpected error occurred while logging in with popup";
            }
        }
    }
}

<div class="auth-container">
    <h1>Sign Up</h1>
    <div *ngIf="isSignedIn">
        <p>An user has signed in, please sign out first.</p>
    </div>
    <div *ngIf="userData && !isSignedIn">
        <p>Signed up complete, and signed in as {{ userData?.getAccount()?.username }}</p>
    </div>
    <div
        *ngIf="isSignedUp && !userData && !showAuthMethodsForRegistration && !showChallengeForRegistration && !showMfaAuthMethods && !showMfaChallenge">
        <p>Sign up completed! Signing you in automatically...</p>
    </div>
    <form
        *ngIf="!showPassword && !showCode && !isSignedIn && !isSignedUp && !showAuthMethodsForRegistration && !showChallengeForRegistration && !showMfaAuthMethods && !showMfaChallenge"
        (ngSubmit)="startSignUp()" autocomplete="off">
        <input type="text" [(ngModel)]="flatUsername" name="flatUsername" placeholder="Username (alias)" />
        <input type="text" [(ngModel)]="firstName" name="firstName" placeholder="First Name" required />
        <input type="text" [(ngModel)]="lastName" name="lastName" placeholder="Last Name" required />
        <input type="text" [(ngModel)]="jobTitle" name="jobTitle" placeholder="Job Title" required />
        <input type="text" [(ngModel)]="city" name="city" placeholder="City" required />
        <input type="text" [(ngModel)]="country" name="country" placeholder="Country" required />
        <input type="email" [(ngModel)]="email" name="email" placeholder="Email" required />
        <button *ngIf="!showPassword && !showCode" type="submit" [disabled]="loading">{{ loading ? 'Signing up...' :
            'Sign Up' }}</button>

        <!-- Separator -->
        <div class="separator">
            <div class="separator-line"></div>
            <span class="separator-text">OR</span>
            <div class="separator-line"></div>
        </div>

        <!-- Social Provider Buttons -->
        <button *ngFor="let provider of socialProviders" type="button" class="social-button"
            (click)="startSignUpWithSocial(provider.domainHint)">
            <img [src]="provider.logo" [alt]="provider.name + ' logo'" class="provider-logo" />
            <span>Sign Up with {{ provider.name }}</span>
        </button>
    </form>

    <!-- Use shared password form -->
    <app-password-form *ngIf="showPassword" [password]="password" [loading]="loading" submitButtonText="Submit Password"
        submitButtonLoadingText="Submitting..." (passwordChange)="password = $event" (submitForm)="submitPassword()">
    </app-password-form>

    <!-- Use shared code form -->
    <app-code-form *ngIf="showCode" [code]="code" [loading]="loading" [resendCountdown]="resendCountdown"
        placeholder="Verification Code" submitButtonText="Verify Code" submitButtonLoadingText="Verifying..."
        (codeChange)="code = $event" (submitForm)="submitCode()" (resend)="resendCode()">
    </app-code-form>

    <!-- Use shared auth method selection form -->
    <app-auth-method-selection-form *ngIf="showAuthMethodsForRegistration" [authMethods]="authMethodsForRegistration"
        [selectedAuthMethod]="selectedAuthMethodForRegistration"
        [verificationContact]="verificationContactForRegistration" [loading]="loading"
        [getPlaceholderText]="getPlaceholderTextForVerificationContact.bind(this)"
        (selectedAuthMethodChange)="selectedAuthMethodForRegistration = $event"
        (verificationContactChange)="verificationContactForRegistration = $event"
        (submitForm)="submitAuthMethodForRegistration()">
    </app-auth-method-selection-form>

    <!-- Use shared challenge form -->
    <app-auth-method-challenge-form *ngIf="showChallengeForRegistration" [challenge]="challengeForRegistration"
        [loading]="loading" (challengeChange)="challengeForRegistration = $event"
        (submitForm)="submitChallengeForRegistration()">
    </app-auth-method-challenge-form>

    <!-- Use shared MFA auth method selection form -->
    <app-mfa-auth-method-selection-form *ngIf="showMfaAuthMethods" [authMethods]="mfaAuthMethods"
        [selectedAuthMethod]="selectedMfaAuthMethod" [loading]="loading"
        (selectedAuthMethodChange)="selectedMfaAuthMethod = $event" (submitForm)="submitMfaAuthMethod()">
    </app-mfa-auth-method-selection-form>

    <!-- Use shared MFA challenge form -->
    <app-mfa-challenge-form *ngIf="showMfaChallenge" [challenge]="mfaChallenge" [loading]="loading"
        (challengeChange)="mfaChallenge = $event" (submitForm)="submitMfaChallenge()">
    </app-mfa-challenge-form>

    <div class="error" *ngIf="error">{{ error }}</div>
</div>
